
- name: Remove previous container dir
  file: path={{ base_container_dir }} state=absent

- file: path={{ repo_dir }} state=directory 

- copy: src=../files/{{ item.name }} dest={{ item.name }} mode={{ item.mode }}
  with_items:
    - { name: '/etc/lxc/default.conf', mode: '0644' }
    - { name: '/etc/network/interfaces.d/lbr01', mode: '0600' }

- service: name=networking state=restarted enabled=yes

- lxc_container: 
    name: '{{ base_container_name }}'
    container_log: true
    template: debian
    template_options: --arch amd64 --release jessie
    state: stopped
    container_command: |
      echo "root:password" | chpasswd
      apt-get update
      apt-get -y upgrade
      apt-get -y install iputils-ping aptitude strace 
      apt-get clean
  environment:
    MIRROR: http://apt.h.ccmp.jp:3142/ftp.us.debian.org/debian
    SECURITY_MIRROR: http://apt.h.ccmp.jp:3142/security.debian.org/

- shell: tar c config rootfs fstab | gzip > {{ repo_dir }}/{{ base_container_name }}.tar.gz
  args:
    chdir: '{{ base_container_dir }}'

- stat: path={{ repo_dir }}/{{ base_container_name }}.tar.gz 
  register: tgz

- shell: touch {{ repo_dir }}/sh1sum-{{ base_container_name }}={{ tgz.stat.checksum }}

- shell: dpkg -l --admindir={{ base_container_dir }}/rootfs/var/lib/dpkg/ > {{ repo_dir }}/dpkg-l-{{ base_container_name }}

