- hosts: mng
  remote_user: root
  vars_files :
    - common_vars.yml
    - network_vars.yml
    - vlan_vars.yml
  vars:
    base_container: lvs-v1-0
    container_name: lvs2-v1-0
    container_dir: "{{ lxc_dir }}/{{ container_name }}"
#    VIRTUAL_SERVER_IP: 10.10.1.110
#    VIRTUAL_SERVER_PORT: 80
    LVS_GLOBAL_IP: "{{ lvs2_global_ip }}"
    LVS_LOCAL_IP: "{{ lvs2_local_ip }}"

  roles:
    - lvs
      
- hosts: lvs02
  remote_user: root
  vars_files:
    - common_vars.yml
  vars:
    container_name: lvs2-v1-0

  roles:
    - deploy
