- hosts: lvs01
  remote_user: root
  vars_files:
    - common_vars.yml
    - network_vars.yml

  roles:
    - { role: ../lvs-web-dr/roles/destroy , site: "{{ lvs.lvs1 }}"  }

- hosts: lvs02
  remote_user: root
  vars_files:
    - common_vars.yml
    - network_vars.yml

  roles:
    - { role: ../lvs-web-dr/roles/destroy , site: "{{ lvs.lvs2 }}"  }

- hosts: web01
  remote_user: root
  vars_files:
    - common_vars.yml
    - network_vars.yml

  roles:
    - { role: ../lvs-web-dr/roles/destroy , site: "{{ web.web1 }}"  }

- hosts: web02
  remote_user: root
  vars_files:
    - common_vars.yml
    - network_vars.yml

  roles:
    - { role: ../lvs-web-dr/roles/destroy , site: "{{ web.web2 }}"  }


