# file:
# - { path: XXX, mode: YYY ,owner: ZZZ ,group: QQQ }
# path: configuration filename 
# src: template filename | default (path) ;default is the same as conf-file   
# mode:  | default(def_perm.fmode) 
# owner: | default(def_perm.owner)
# group: | default(def_perm.group)
# copy: bool | default(true) ; if false , not applied template.
#
# Please use flow-style for readability of results of diff.
#

def_perm:
  fmode: '0644'
  owner: 'root'
  group: 'root'

common_config:
  template:
    src_dir: 'template/common'
    file:
      - { path: '/etc/hostname', mode: '0644' }
    
lvs_config:
  template:
    src_dir: 'template/lvs'
    file:
 #     - { path: '/etc/hostname', mode: '0644' }
      - { path: '/etc/network/interfaces', mode: '0644' }
      - { path: '/etc/keepalived/keepalived.conf', mode: '0644' }
      - { path: '/work/lvs-setup.sh', mode: '0755' }
      - { path: '/etc/systemd/system/lvs-setup.service', mode: '0644' }
      - { path: '/etc/network/if-up.d/iptables', mode: '0755' }
      
web_config:
  template:
    src_dir: 'template/web'
    file:
#      - { path: '/etc/hostname', mode: '0644' }
      - { path: '/etc/network/interfaces', mode: '0644' }
      - { path: '/var/www/html/index.html', mode: '0644' }
      - { path: '/work/web-setup.sh', mode: '0755' }
      - { path: '/etc/systemd/system/web-setup.service', mode: '0644' }

haproxy_config:
  template:
    src_dir: 'template/haproxy'
    file:
      - { path: '/etc/network/interfaces', mode: '0644' }
      
common_lxcconfig:
  template:
    src_dir: 'template/commonlxc'
    file:
      - { path: 'fstab', mode: '0644' }
      
lvs_lxcconfig:
  template:
    src_dir: 'template/lvslxc'
    file:
      - { path: 'config', mode: '0644' }
    
web_lxcconfig:
  template:
    src_dir: 'template/weblxc'
    file:
      - { path: 'config', mode: '0644' }
      
haproxy_lxcconfig:
  template:
    src_dir: 'template/haproxylxc'
    file:
      - { path: 'config', mode: '0644' }

  