- name: Create root directory
  file: path={{ config_root }} state=directory recurse=yes
    
- set_fact:
    conf_template: "{{ conf.template | default ({}) }}"
    conf_copyonly: "{{ conf.copyonly | default ({}) }}"
    
- name: Create diretory tree 
  file: >
    path={{ config_root }}/{{ item.path | dirname }}
    state=directory
    recurse=yes   
  with_items:
    - "{{ conf_template.file | default([]) }}"
    - "{{ conf_copyonly.file | default([]) }}"
  when: item.path 

- name: Create configuration files from template.
  template: > 
    src={{ conf_template.src_dir }}/{{ item.src | default(item.path)  }}
    dest={{ config_root }}/{{ item.path }}
    mode={{ item.mode | default(def_perm.fmode) }}
  with_items: "{{ conf_template.file | default([]) }}"
  when: item.path | default(false) and item.copy | default(true) 

- name: Copy configuration file only. 
  copy: > 
    src={{ conf_copyonly.src_dir }}/{{ item.src | default(item.path)  }}
    dest={{ config_root }}/{{ item.path }}
    mode={{ item.mode | default(def_perm.fmode) }}
  with_items: "{{ conf_copyonly.file | default([]) }}"
  when: item.path | default(false) and item.copy | default(true) 
