
- file: path={{ container_dir }} state=absent
- file: path={{ container_dir }} state=directory
- file: path={{ repo_dir }} state=directory 

- shell: tar xfz {{ repo_dir }}/{{ base_container }}.tar.gz
  args:
    chdir: '{{ container_dir }}'

- template: src=../files/var/lib/lxc/config dest={{ container_dir }}/config mode='0644'

- template: src=../files/{{ item.name }} dest={{ container_dir }}/rootfs/{{ item.name }} mode={{ item.mode }}
  with_items:
    - { name: '/etc/hostname', mode: '0600' }
    
- lxc_container: 
    name: '{{ container_name }}'
    container_log: true
    template: debian
    template_options: --arch amd64 --release jessie
    state: stopped
    container_command: |
      apt-get update
      apt-get -y install apache2 iptables strace aptitude
      apt-get clean
      systemctl enable apache2 
  environment:
    MIRROR: http://apt.h.ccmp.jp:3142/debian


- shell: tar c config rootfs fstab | gzip > {{ repo_dir }}/{{ container_name }}.tar.gz
  args:
    chdir: '{{ container_dir }}'

