- name: Create container directory
  file: path={{ container_dir }} state=directory
- name: Extract base container
  shell: tar xfz {{ repo_dir }}/{{ base_container }}.tar.gz
  args:
    chdir: '{{ container_dir }}'
    
- name: Copy hostname
  copy: >
    src={{ personal_conf_dir }}/rootfs/{{ item.name }}
    dest={{ container_dir }}/rootfs/{{ item.name }} mode={{ item.mode }}
  with_items:
  - name: '/etc/hostname'
    mode: '0644'
    
- name: Copy config for temporarily running on the manager 
  template: >
    src={{ personal_conf_dir }}/config.mng
    dest={{ container_dir }}/config
    mode='0644'
  
- name: run container
  lxc_container:
    name: "{{ container_name }}"
    state: stopped
    
#- name: Create lxc config for production
#  copy: >
#    src={{ personal_conf_dir }}/config
#    dest={{ container_dir }}/config
#    mode=0644

- name: Archive rootfs for copy
  shell: tar c rootfs | gzip > {{ archive_dir }}/{{ container_name }}.tar.gz
  args:
    chdir: '{{ container_dir }}'    

#- name: Recopy config for temporarily running on the manager 
#  copy: >
#    src={{ personal_conf_dir }}/config.mng
#    dest={{ container_dir }}/config
#    mode='0644'
    
- name: destroy container
  lxc_container:
    name: "{{ container_name }}"
    state: absent

- name: fetch rootfs archive
  fetch: >
    src={{ archive_dir }}/{{ container_name }}.tar.gz
    dest={{ local_archive_dir }}/
    flat=yes