- name: Create repository directory
  file: path={{ repo_dir }} state=directory

- name: Create archive directory
  file: path={{ archive_dir }} state=directory

- name: Check whether interfaces.d/ is used.
  shell: grep -E "^ *source-directory */etc/network/interfaces.d *" /etc/network/interfaces > /dev/null
  register: greprc
  changed_when: greprc.rc != 0

- name: Let interfaces.d/ used
  lineinfile: >
    dest=/etc/network/interfaces 
    line="source-directory /etc/network/interfaces.d"
    create=yes
  when: greprc.rc != 0

- name: Copy Network config
  template: >
    src=files/mnghost/etc/network/interfaces.d/lbrX
    dest=/etc/network/interfaces.d/{{ item.name }}
    mode=0644
  with_items: mnghost.bridge
  notify: restart network
  
- name: Copy LXC default.conf
  template: >
    src=files/mnghost/{{ item.name }}
    dest={{ item.name }}
    mode={{ item.mode }}
  with_items:
    - { name: '/etc/lxc/default.conf', mode: '0644' }
 
- name: Port forward enable
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes

- name: Port forward enable permanetly
  copy: src=files/mnghost/{{ item.name }} dest={{ item.name }} mode={{ item.mode }}
  with_items:
    - { name: '/etc/sysctl.d/forward.conf', mode: '0644' }
