- name: Create container directory
  file: path={{ container_dir }} state=directory
- name: Extract base container
  shell: tar xfz {{ repo_dir }}/{{ base_container }}.tar.gz
  args:
    chdir: '{{ container_dir }}'

- name: Edit hostname
  template: src=../files/{{ item.name }} dest={{ container_dir }}/rootfs/{{ item.name }} mode={{ item.mode }}
  with_items:
  - name: '/etc/hostname'
    mode: '0644'
    
- name: Edit config for temporarily running on the manager 
  template: >
    src=../files/var/lib/lxc/config.mng
    dest={{ container_dir }}/config
    mode='0644'
      
- name: Create Directory for Web Setup
  file: state=directory path={{ container_dir }}/rootfs/work
    
- name: Web Setup
  template: >
    src=../files/{{ item.name }} 
    dest={{ container_dir }}/rootfs/{{ item.name }}
    owner=root
    group=root
    mode={{ item.mode }}
  with_items:
    - name: '/work/web-setup.sh'
      mode: '0755'
    - name: '/etc/systemd/system/web-setup.service'
      mode: '0644'
        
- name: Enable web-setup.service
  file: >
    path='{{ container_dir }}/rootfs/etc/systemd/system/multi-user.target.wants/web-setup.service'
    src='../web-setup.service'
    state=link

- name: Setup index.html
  template: >
    src=../files/{{ item.name }}
    dest={{ container_dir }}/rootfs/{{ item.name }}
    owner=root
    group=root
    mode={{ item.mode }}
  with_items:
    - name: '/var/www/html/index.html'
      mode: '0644'

- name: run container
  lxc_container:
    name: "{{ container_name }}"
    state: stopped

- name: Create lxc config for production  
  template: >
    src=../files/var/lib/lxc/config.prd
    dest={{ container_dir }}/config.prd
    mode='0644'

- name: Archive rootfs for copy
  shell: tar c config.prd rootfs | gzip > {{ archive_dir }}/{{ container_name }}.tar.gz
  args:
    chdir: '{{ container_dir }}'

- name: destroy container
  lxc_container:
    name: "{{ container_name }}"
    state: absent

- name: fetch rootfs archive
  fetch: >
    src={{ archive_dir }}/{{ container_name }}.tar.gz
    dest={{ local_archive_dir }}/
    flat=yes
    