- hosts: lvs01
  gather_facts: False
  remote_user: root
  vars_files:
    - vars/common.yml
    - vars/config.yml
  vars:
    pcon: "{{ lvs.lvs1 }}"

  pre_tasks:
    - name: stat container
      shell: lxc-info -n {{ pcon.container_name }}
      register: lxc_info
      failed_when: lxc_info.rc not in [0,1]
      changed_when: lxc_info.rc == 1
  roles:
    - { role: ../lvs-web-dr/roles/create, when: "lxc_info.rc == 1", delegate_to: "{{ lxchost.manager_host }}", site: "{{ pcon }}" }
    - { role: ../lvs-web-dr/roles/deploy, when: "lxc_info.rc == 1", site: "{{ pcon }}" }
    - { role: ../lvs-web-dr/roles/lvs_post, site: "{{ pcon }}" }
    - { role: ../lvs-web-dr/roles/start, site: "{{ pcon }}" }

- hosts: lvs02
  gather_facts: False
  remote_user: root
  vars_files:
    - vars/common.yml
    - vars/config.yml
  vars:
    pcon: "{{ lvs.lvs2 }}"

  pre_tasks:
    - name: stat container
      shell: lxc-info -n {{ pcon.container_name }}
      register: lxc_info
      failed_when: lxc_info.rc not in [0,1]
      changed_when: lxc_info.rc == 1
  roles:
    - { role: ../lvs-web-dr/roles/create, when: "lxc_info.rc == 1", delegate_to: "{{ lxchost.manager_host }}", site: "{{ pcon }}" }
    - { role: ../lvs-web-dr/roles/deploy, when: "lxc_info.rc == 1", site: "{{ pcon }}" }
    - { role: ../lvs-web-dr/roles/lvs_post, site: "{{ pcon }}" }
    - { role: ../lvs-web-dr/roles/start, site: "{{ pcon }}" }



