- hosts: service1-all
  gather_facts: False
  remote_user: root
  vars_files:
    - vars/common.yml
    - vars/config.yml
  vars:
    pcon: "{{ container[contents['service1']] }}"

  roles:
    - { role: ../lvs-web-dr/roles/destroy , site: "{{ pcon }}"  }
