- name: stat config top directory
  stat: path={{ config_dir }}
  register: rc
  failed_when: rc.stat.isdir == 'false'

- name: Create personal config directory
  file: path={{ config_dir }}/{{ container_name }} state=directory

- name: Create diretory tree
  file:
    path=config/{{ container_name }}/{{ item }} state=directory recurse=yes
  with_items:
    - "etc"
    - "etc/network"
    - "etc/keepalived"
    - "etc/systemd/system/"
    - "work"
    - "var/lib/lxc"
    
- name: Create hostname file
  template: src=../files/{{ item.name }} dest={{ personal_conf_dir }}/{{ item.name }} mode={{ item.mode }}
  with_items:
  - name: '/etc/hostname'
    mode: '0644'
    
- name: Create Keepalived config
  template: >
    src=../files/{{ item.name }}
    dest={{ personal_conf_dir }}/{{ item.name }}
    mode={{ item.mode }}
    owner=root
    group=root
  with_items:
    - name: '/etc/keepalived/keepalived.conf'
      mode: '0644'

- name: Create LVS Setup shell file
  template: >
    src='../files/{{ item.name }}' 
    dest='{{ personal_conf_dir }}/{{ item.name }}'
    owner=root
    group=root
    mode='{{ item.mode }}'
  with_items:
    - name: '/work/lvs-setup.sh'
      mode: '0755'
    - name: '/etc/systemd/system/lvs-setup.service'
      mode: '0644'
        
- name: Create lxc config for production
  template: >
    src=../files/{{ item.name }}
    dest={{personal_conf_dir}}/{{ item.name }}
  with_items:
    - name: '/var/lib/lxc/config.prd'
      mode: '0644'
