- hosts: mng
  remote_user: root
  vars_files :
    - common_vars.yml
    - network_vars.yml
  vars:
    base_container: lvs-v1-0
    container_name: lvs1-v1-0
    container_dir: "{{ lxc_dir }}/{{ container_name }}"
#    VIRTUAL_SERVER_IP: 10.10.1.110
#    VIRTUAL_SERVER_PORT: 80
    LVS_VLAN1_IP: "{{ lvs1_vlan1_ip }}"
    LVS_MYVLAN_IP: "{{ lvs1_myvlan_ip }}"

  roles:
    - lvscnt
      
- hosts: lvs01
  remote_user: root
  vars_files:
    - common_vars.yml
  vars:
    container_name: lvs1-v1-0

  roles:
    - deploy