- hosts: mng
  vars_files:
    - common_vars.yml
    - network_vars.yml
  vars:
    base_container: web-v1-0
    container_name: web2-v1-0
    container_dir: "{{ lxc_dir }}/{{ container_name }}"
    
    WEB_IP: "{{ web2_ip }}"
  roles:
    - webcnt

- hosts: web02
  remote_user: root
  vars_files:
    - common_vars.yml
  vars:
    container_name: web2-v1-0

  roles:
    - deploy
    

      