config_dir: config

service:
  name: service1
  vlanid: 10
  
container:
#Lvs
  lvs1:
    base_container: lvs-v1-0
    container_name: lvs1-s1
  lvs2:
    base_container: lvs-v1-0
    container_name: lvs2-s1
    hostname: lvs2-s1
#Web
  web1:
    base_container: web-v1-0
    container_name: web1-s1
    hostname: web1
  web2:
    base_container: web-v1-0
    container_name: web2-s1
    hostname: web2
