- name: stat config top directory
  stat: path=config
  register: rc
  failed_when: rc.stat.isdir == 'false'

- name: Create personal config directory
  file: path=config/{{ container_name }} state=directory

- name: Create diretory tree
  file:
    path=config/{{ container_name }}/{{ item }} state=directory recurse=yes
  with_items:
    - "etc"
    - "etc/systemd/system/"
    - "work"
    - "var/lib/lxc"
    - "var/www/html"

- name: Create hostname file.
  template: >
    src=../files/{{ item.name }}
    dest={{ personal_conf_dir }}/{{ item.name }} mode={{ item.mode }}
  with_items:
  - name: '/etc/hostname'
    mode: '0644'
          
    
- name: Create Web Setup shell file.
  template: >
    src=../files/{{ item.name }} 
    dest={{ personal_conf_dir }}/{{ item.name }}
    owner=root
    group=root
    mode={{ item.mode }}
  with_items:
    - name: '/work/web-setup.sh'
      mode: '0755'
    - name: '/etc/systemd/system/web-setup.service'
      mode: '0644'
        
- name: Create index.html.
  template: >
    src=../files/{{ item.name }}
    dest={{ personal_conf_dir }}/{{ item.name }}
    owner=root
    group=root
    mode={{ item.mode }}
  with_items:
    - name: '/var/www/html/index.html'
      mode: '0644'

- name: Create lxc config for production
  template: >
    src=../files/{{ item.name }}
    dest={{personal_conf_dir}}/{{ item.name }}
  with_items:
    - name: '/var/lib/lxc/config.prd'
      mode: '0644'
