- name: Copy container archive
  copy: >
    src={{ local_archive_dir }}/{{ container_name }}.tar.gz
    dest={{ remote_archive_dir }}/{{ container_name }}.tar.gz
    
- name: Remove privious container directory
  file: path={{ lxc_dir }}/{{ container_name }} state=absent
    
- name: Create container directory
  file: path={{ lxc_dir }}/{{ container_name }} state=directory
  
- name: Extract container archive
  shell: tar xfz {{ remote_archive_dir }}/{{ container_name }}.tar.gz
  args:
    chdir: '{{ lxc_dir }}/{{ container_name }}'
    
- name: Remove archive 
  file: path={{ remote_archive_dir }}/{{ container_name }}.tar.gz state=absent
  
- name: Rename config filename 
  shell: mv config.prd config
  args:
    chdir: '{{ lxc_dir }}/{{ container_name }}'

#  - name: Load ip_vs modules on host
#    shell: modprobe ip_vs
#    
- name: Start Container
  shell: lxc-start -n {{ container_name }} -d

- name: Remove local archive
  file: path={{ local_archive_dir }}/{{ container_name }}.tar.gz state=absent
  delegate_to: 127.0.0.1
  