- hosts: mng
  gather_facts: False
  remote_user: root
  vars_files :
    - vars/common.yml
    - vars/config.yml
  roles:
    - { role: ../lvs-web-dr/roles/web_pre , site: "{{ web.web1 }}" }
    - { role: ../lvs-web-dr/roles/web_pre , site: "{{ web.web2 }}" }
            
- hosts: web01
  gather_facts: False
  remote_user: root
  vars_files:
    - vars/common.yml
    - vars/config.yml
  vars:
    pcon: "{{ web.web1 }}"
  pre_tasks:
    - name: stat container
      shell: lxc-info -n {{ pcon.container_name }}
      register: lxc_info
      failed_when: lxc_info.rc not in [0,1]
      
  roles:
    - role: ../lvs-web-dr/roles/deploy
      when: "lxc_info.rc == 1"
      site: "{{ pcon }}"  
    - { role: ../lvs-web-dr/roles/web_post , site: "{{ pcon }}"  }

- hosts: web02
  gather_facts: False
  remote_user: root
  vars_files:
    - vars/common.yml
    - vars/config.yml
  vars:
    pcon: "{{ web.web2 }}"
  pre_tasks:
    - name: stat container
      shell: lxc-info -n {{ pcon.container_name }}
      register: lxc_info
      failed_when: lxc_info.rc not in [0,1]
      
  roles:
    - role: ../lvs-web-dr/roles/deploy
      when: "lxc_info.rc == 1"
      site: "{{ pcon }}"  
    - { role: ../lvs-web-dr/roles/web_post , site: "{{ pcon }}"  }





