- hosts: service2-web1
  connection: local
  gather_facts: False
  remote_user: root
  vars_files :
    - vars/config.yml
    - vars/var_config.yml
    - vars/template.yml

  vars:
    site: "{{ personal_config.web1 }}"
    pcon: "{{ container.web1 }}"
    container_name: "{{ pcon.container_name }}"
    hostname: "{{ pcon.hostname | default(container_name) }}"
    
  pre_tasks:
    - name: Create config directory
      file: path={{ config_dest }} state=directory

  roles:
    - role: config
      config_root: "{{ config_dest }}/{{ container_name }}/rootfs"
      conf: "{{ web_config }}"
      
    - role: config
      config_root: "{{ config_dest }}/{{ container_name }}"
      conf: "{{ web_lxcconfig }}"

