#Lvs
lvs:
  lvs1:
    base_container: lvs-v1-0
    container_name: lvs1-s1
  lvs2:
    base_container: lvs-v1-0
    container_name: lvs2-s1
#Web
web:
  web1:
    base_container: web-v1-0
    container_name: web1-s1
  web2:
    base_container: web-v1-0
    container_name: web2-s1

