- name: Remove previous container dir
  file: path={{ container_dir }} state=absent

- file: path={{ repo_dir }} state=directory 

- lxc_container: 
    name: '{{ container_name }}'
    container_log: true
    template: debian
    template_options: --arch amd64 --release jessie
    state: stopped
    container_command: |
      echo "root:password" | chpasswd
      apt-get update
      apt-get -y upgrade
      {% if pkgs %}
      apt-get -y install {{ pkgs | join(" ") }}
      {% endif %} 
      apt-get clean
  environment: "{{ apt_mirror_env | default({}) }}"
    
- file: >
    path={{ container_dir }}/rootfs/{{ item.name }}
    mode={{ item.mode }}
    state=directory
  with_items:
    - { name: '/root/.ssh/', mode: '0700' }

- template: >
    src=files/base/{{ item.name }}
    dest={{ container_dir }}/rootfs/{{ item.name }}
    mode={{ item.mode }}
  with_items:
    - { name: '/root/.ssh/authorized_keys', mode: '0644' }

- shell: tar c config rootfs fstab | gzip > {{ repo_dir }}/{{ container_name }}.tar.gz
  args:
    chdir: '{{ container_dir }}'

- shell: dpkg-query -W -f='${binary:Package}\t\t\t${Version}\n' --admindir={{ container_dir }}/rootfs/var/lib/dpkg/ > {{ repo_dir }}/.pkgs.{{ container_name }}

