- hosts: lvshost
  connection: local
  gather_facts: False
  remote_user: root
  vars_files :
    - vars/common.yml
    - vars/config.yml
    - vars/template.yml
  vars:
    pcon: "{{ container[contents[service.name]] }}"

  roles:
    - role: ../lvs-web-dr/roles/config
      site: "{{ pcon }}"
      conf: "{{ lvs_config }}"
      lxcconf: "{{ lvs_lxcconfig }}"
#    - role: ../lvs-web-dr/roles/config
#      site: "{{ lvs.lvs2 }}"
#      conf: "{{ lvs_config }}"
#      lxcconf: "{{ lvs_lxcconfig }}"

