- hosts: cluster
  gather_facts: False
  remote_user: root
  vars_files:
    - vars/common.yml
    - vars/config.yml
  vars:
    pcon: "{{ container[contents[service.name]] }}"

  roles:
    - { role: ../lvs-web-dr/roles/destroy , site: "{{ pcon }}"  }

#- hosts: lvs02
#  gather_facts: False
#  remote_user: root
#  vars_files:
#    - vars/common.yml
#    - vars/config.yml
#
#  roles:
#    - { role: ../lvs-web-dr/roles/destroy , site: "{{ lvs.lvs2 }}"  }
#
#- hosts: web01
#  gather_facts: False
#  remote_user: root
#  vars_files:
#    - vars/common.yml
#    - vars/config.yml
#   
#  roles:
#    - { role: ../lvs-web-dr/roles/destroy , site: "{{ web.web1 }}"  }
#- hosts: web02
#  gather_facts: False
#  remote_user: root
#  vars_files:
#   - vars/common.yml
#   - vars/config.yml
#   
#  roles:
#    - { role: ../lvs-web-dr/roles/destroy , site: "{{ web.web2 }}"  }


