- hosts: service2-web
  gather_facts: False
  remote_user: root
  vars_files:
    - vars/common.yml
    - vars/config.yml
  vars:
    pcon: "{{ container[contents['service2']] }}"

  roles:
    - { role: ../lvs-web-dr/roles/web_post, site: "{{ pcon }}" }

  post_tasks:
    - name: start container
      lxc_container:
        name: "{{ pcon.container_name }}"
        state: started


