- name: Stop and destroy provious container
  lxc_container:
    name: "{{ container_name }}"
    state: absent
      
- name: Remove privious container directory
  file: path={{ container_dir }} state=absent
    
- name: Create container directory
  file: path={{ container_dir }} state=directory
  
- name: Extract container archive
  unarchive: >
    src={{ repo_dir }}/{{ base_container }}.tar.gz
    dest={{ container_dir }}

- name: Create lxc config for this host. 
  template: >
    src={{ personal_conf_dir }}/config
    dest={{ container_dir }}/config
    mode='0644'
  