- hosts: service1-lvs
  gather_facts: False
  remote_user: root
  vars_files:
    - vars/config.yml
  vars:
    pcon: "{{ container[contents[service.name]] }}"
    cname: "{{ contents[service.name] }}"

# check whether the container have been deployed already.
  pre_tasks:
    - shell: lxc-info -n {{ pcon.container_name }}
      register: lxc_info
      failed_when: lxc_info.rc not in [0,1]
      changed_when: lxc_info.rc == 1
      
# container's common processing.
  roles:
    - { role: deploy, when: "lxc_info.rc == 1", site: "{{ pcon }}" }
    - { role: common_post, site: "{{ pcon }}" }
    - { role: lvs_post, site: "{{ pcon }}" }

# container's specific processing.
  tasks:
   - include: "lvs1.yml"
     when: cname == "lvs1"
   - include: "lvs2.yml"
     when: cname == "lvs2"
     
# To start container as long as it did not start so far.     
  post_tasks:
    - name: start container
      lxc_container:
        name: "{{ pcon.container_name }}"
        state: started

