---
- hosts: service1-lvs
  gather_facts: False
  remote_user: root

  vars_files:
    - config/config.yml
  vars:
    site: "{{ container[cname] }}"
    container_name: "{{ site.container_name }}"

# check whether the container have been deployed already.
  pre_tasks:
    - shell: lxc-info -s -H -n {{ container_name }}
      register: lxc_info
      failed_when: lxc_info.rc not in [0,1]
      changed_when: lxc_info.rc == 1
      
# container's common processing.
  roles:
    - { role: deploy, when: "lxc_info.rc == 1" }
    - { role: common_post}
    - { role: lvs_post }
# container's specific processing(if necessary)
#   - { role: lvs1, when: "cname == 'lvs1'" }
#   - { role: lvs2, when: "cname == 'lvs2'" }

#
# To start container as long as it did not start so far.
  post_tasks:
    - lxc_container:
        name: "{{ container_name }}"
        state: started


