---
- hosts: service1-web
  gather_facts: False
  remote_user: root

  vars_files:
    - config/config.yml
  vars:
    site: "{{ container[cname] }}"
    container_name: "{{ site.container_name }}"
    personal_conf_dir: "{{ config_dir }}/{{ container_name }}"
    container_dir: "{{ lxc_dir }}/{{ container_name }}"

# check whether the container have been deployed already.
  pre_tasks:
    - shell: lxc-info -s -H -n {{ container_name }}
      register: lxc_info
      failed_when: lxc_info.rc not in [0,1]
      changed_when: lxc_info.rc == 1
      
# container's common processing.
  roles:
    - { role: deploy, when: "lxc_info.rc == 1" }
    - { role: common_post}
    - { role: web_post }
# container's specific processing(if necessary).
#   - { role: web1, when: "cname == 'web1'" }
#   - { role: web2, when: "cname == 'web2'" }


# To start container as long as it did not start so far.
  post_tasks:
    - lxc_container:
        name: "{{ container_name }}"
        state: started
#
        

