---
- hosts: service2-lvs2
  gather_facts: False
  remote_user: root

  vars_files:
    - config/config.yml
  vars:
    site: "{{ container.lvs2 }}"
    container_name: "{{ site.container_name }}"
#    hostname: "{{ site.hostname | default(site.container_name) }}"
#    personal_conf_dir: "{{ config_dir }}/{{ container_name }}"    

# check whether the container have been deployed already.
  pre_tasks:
    - shell: lxc-info -n {{ container_name }}
      register: lxc_info
      failed_when: lxc_info.rc not in [0,1]
      changed_when: lxc_info.rc == 1
      
# container's common processing.
  roles:
    - { role: deploy, when: "lxc_info.rc == 1" }
    - { role: common_post}
    - { role: lvs_post }

# container's specific processing.
  tasks:
    - debug: msg="describe container's specific tasks here"
# - task1
# - task2
# ...

# end of container's specific tasks
#
# To start container as long as it did not start so far.
  post_tasks:
    - lxc_container:
        name: "{{ container_name }}"
        state: started


