---
- hosts: service2-web1
  gather_facts: False
  remote_user: root

  vars_files:
    - config/config.yml
  vars:
    site: "{{ container.web1 }}"
    container_name: "{{ site.container_name }}"
    personal_conf_dir: "{{ config_dir }}/{{ container_name }}"
    container_dir: "{{ lxc_dir }}/{{ container_name }}"

# check whether the container have been deployed already.
  pre_tasks:
    - shell: lxc-info -n {{ container_name }}
      register: lxc_info
      failed_when: lxc_info.rc not in [0,1]
      changed_when: lxc_info.rc == 1
      
# container's common processing.
  roles:
    - { role: deploy, when: "lxc_info.rc == 1" }
    - { role: common_post}
    - { role: web_post }

# container's specific processing.
  tasks:
    - debug: msg="describe container's specific tasks here"
    - copy: >
        src={{ personal_conf_dir }}/rootfs/{{ item.name }}
        dest={{ container_dir }}/rootfs/{{ item.name }}
        mode={{ item.mode }}
        owner={{ item.owner }}
        group={{ item.group }}
      with_items:
        - { name: '/etc/apache2/mods-available/status.conf', mode: '0644', owner: 'root', group: 'root' }
      notify:
        - reload apache2
# - task2
# ...

# end of container's specific tasks
#
# To start container as long as it did not start so far.
  post_tasks:
    - lxc_container:
        name: "{{ container_name }}"
        state: started
#
  handlers:
    - name: reload apache2
      lxc_container:
        name: "{{ container_name }}"
        state: started
        container_command: |
          systemctl reload apache2
        

