vrrp:
  global_vip: 10.10.1.10
  local_vip: 192.168.10.10
  auth_password: password

lvscommon:
  vip: 10.10.1.110
  port: 80
  ip: "{{ vrrp.local_vip }}"
  
#Web(real server)
realserver:
  subnet: 24
  server1:
    ip: 192.168.10.51
    port: 80
  server2:
    ip: 192.168.10.52
    port: 80
    
#Lvs
container:
  lvs1:
    base_container: lvs-v1-0
    container_name: lvs1-s1
    global_ip: 10.10.1.11/24
    local_ip: 192.168.10.11/24
  lvs2:
    base_container: lvs-v1-0
    container_name: lvs2-s1
    hostname: lvs2-s1
    global_ip: 10.10.1.12/24
    local_ip: 192.168.10.12/24
#Web
#web:
  web1:
    base_container: web-v1-0
    container_name: web1-s1
    hostname: web1
    local_ip: "{{ realserver.server1.ip }}/{{ realserver.subnet }}"
    local_port: "{{ realserver.server1.port }}"
  web2:
    base_container: web-v1-0
    container_name: web2-s1
    hostname: web2
    local_ip: "{{ realserver.server2.ip }}/{{ realserver.subnet }}"
    local_port: "{{ realserver.server2.port }}"
