# Usage:
#  ansible-playbook -i ./development ./lvs.yml -v
#

- hosts: mng
  remote_user: root

  vars:
    repo_dir: /work/image
    lxc_dir: /var/lib/lxc

    base: {
      "container_name": "base-v1-0", 
      container_dir: '{{ lxc_dir }}/{{ container_name }}'
    }

    middle: {
      container_name: base_lvs-v1-0, 
      container_dir: '{{ lxc_dir }}/{{ container_name }}',
      pkgs: 'ipvsadm iptables keepalived',
      extra_tasks: 'systemctl enable keepalived'
    }

  pre_tasks:
    - stat: path={{ repo_dir }}/{{ base.container_name }}.tar.gz
      register: base_tgz

    - stat: path=/usr/bin/lxc-create
      register: lxc_create

  roles:
    - { role: common, when: "lxc_create.stat.xoth == 'False'" }
    - { role: base, when: "base_tgz.stat.exists == 'False'" }
    - base_middle

