# Usage:
#  ansible-playbook -i ./inventory/development ./web.yml -v
#

- hosts: mng
  remote_user: root

  vars:
    repo_dir: "{{ manager.repo_dir }}"
    lxc_dir: "{{ lxchost.lxc_dir }}"

    base_container_name: base-v1-0
    middle_container_name: web-v1-0 

    base_container_dir: '{{ lxc_dir }}/{{ base_container_name }}'
    middle_container_dir: '{{ lxc_dir }}/{{ middle_container_name }}'
    pkgs: 'apache2 iptables'
    extra_tasks: 'systemctl enable apache2'

  pre_tasks:
    - stat: path={{ repo_dir }}/{{ base_container_name }}.tar.gz
      register: base_tgz

  roles:
    - { role: base, when: not base_tgz.stat.exists }
    - middle

