#!/bin/bash

LOCAL_NET={{ "10.0.0.0" | to_con_addr(service.id) }}/16

if ! iptables -t nat -C POSTROUTING -o eth0 --src ${LOCAL_NET} -j MASQUERADE ; then
        iptables -t nat -A POSTROUTING -o eth0 --src ${LOCAL_NET} -j MASQUERADE
fi

