- copy: src=../files/{{ item.name }} dest={{ item.name }} mode={{ item.mode }}
  with_items:
    - { name: '/etc/apt/sources.list', mode: '0644' }
    - { name: '/etc/apt/preferences', mode: '0644' }

- apt: name={{ item }} state=present update_cache=yes
  with_items:
    - lxc=1:1.0.7-10 
    - lxc-dev
    - less
    - bridge-utils
    - python-dev
    - python-setuptools
    - gcc
    - tcpdump
    - strace
    - ca-cacert

- easy_install: name=pip

- pip: name=lxc-python2 state=latest

#- sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes

