
- file: path={{ container_dir }} state=absent
- file: path={{ container_dir }} state=directory
- file: path={{ repo_dir }} state=directory 

- shell: tar xfz {{ repo_dir }}/{{ base_container_name }}.tar.gz
  args:
    chdir: '{{ container_dir }}'

- template: >
    src=files/lxc/config
    dest={{ container_dir }}/config mode='0644'

- template: >
    src=files/middle/{{ item.name }}
    dest={{ container_dir }}/rootfs/{{ item.name }}
    mode={{ item.mode }}
  with_items:
    - { name: '/etc/hostname', mode: '0600' }
    
- lxc_container: 
    name: '{{ container_name }}'
    container_log: true
    state: stopped
    container_command: |
      apt-get update
      {% if pkgs  %}
      apt-get -y install {{ pkgs | join(" ") }}
      {% endif %}
      apt-get clean
      {% for item in extra_tasks %}
      {{ item }}
      {% endfor %}
  environment: "{{ apt_mirror_env | default({}) }}"
  
- shell: tar c config rootfs fstab | gzip > {{ repo_dir }}/{{ container_name }}.tar.gz
  args:
    chdir: '{{ container_dir }}'

- stat: path={{ repo_dir }}/{{ container_name }}.tar.gz 
  register: tgz

- shell: dpkg-query -W -f='${binary:Package}\t\t\t${Version}\n' --admindir={{ container_dir }}/rootfs/var/lib/dpkg/ > {{ repo_dir }}/.pkgs.{{ container_name }}
