mnghost:
  bridge:
    - name: "lbr01"
      iface: "eth0"
      ip: "192.168.10.254"
      mask: "255.255.255.0"
  lxc_default:
    iface: "lbr01"
    ip: "192.168.10.101/24" # address/mask(8,16,...)
    gateway: "192.168.10.254"
    